services:
  mariadb:
    image: mariadb:lts
    hostname: mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DB}
  adminer:
    image: adminer
    hostname: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
  ezsched:
    image: ezsched
    hostname: ezsched
    container_name: ezsched
    restart: always
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    environment:
      MARIADB_URI: ${MARIADB_URI}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DB}